### ISSUE TITLE
Basic & Core:  peb.setDefault throw errors

### ISSUE THREAD

**Issue by TheColdPot** [TechPot-Studio/peb.js#2]
**Affect Version/s**: ? - 2.2.0
### Where Did The Error Occur? 
- [ ] Ajax data transmission
- [x] Alternative functions for native JS
- [x] Basic and core functions
- [x] Web DOM manipulation
- [ ] Mathematical operations
### Description
When using the following code
```js
peb.setDefault(peb.sel)
```
Will throw an error
```
Uncaught TypeError: Cannot set property 'platform' of undefined
at peb.js:87:26
    at Array.forEach (peb.js)
    at Function.peb.setDefault (peb.js:86:31)
    at <anonymous>:1:5
```
I can basically be sure that this is a bug.

**Comment by TheColdPot** [comment]
I think overly old-fashioned methods are used in the code
```js
    peb.setDefault = function ( func ) {
        let backup = peb;
        peb = func;
        Object.keys( backup ).forEach( function ( current ) {
            peb[current] = backup[current]
        } );
        // Return to destroy variable
        return func;
    }
```

**Comment by TheColdPot** [comment]
After I checked the code carefully, I found that it was my fault. I actually wrote `peb.sel` as `peb.peb`
